name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      waves-private-node:
        image: wavesplatform/waves-private-node:latest
        ports:
          - 6869:6869
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: .nvmrc
      - run: yarn install --frozen-lockfile
      - run: yarn run prettier
      - run: yarn run typecheck
      - run: |
          yarn build
          yarn link
          yarn link vitest-environment-waves
      - run: yarn run test
        env:
          CI: true
